---
title: "Parameter Estimation"
author: "Lory Salazar"
date: "3/3/2021"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(here)
library(boot)
library(gt)
library(patchwork)
library(broom)
library(nlstools)
library(janitor)
library(kableExtra)
```

```{r}
# Read in the data and add a column to assign numerical values to the years
fish_catch <- read.csv(here("data","fish_catch.csv"), skip = 2) %>% 
  drop_na() %>% 
  clean_names() %>% 
  mutate(year_number = 0:62) 

# Changing from character to numeric class
fish_catch$wild_catch <- as.numeric(fish_catch$wild_catch)
fish_catch$year <- as.numeric(fish_catch$year)

```

```{r}
# Creating an exploratory plot to look at fish catches over time
ggplot(data = fish_catch, aes(x = year_number, y = wild_catch)) +
  geom_point() +
  theme_minimal() +
  scale_y_continuous(breaks = c(10,20,30,40,50,60,70,80,90,100))

# Finding initial estimates 
fish_exp <- fish_catch %>% 
  mutate(ln_wild = log(wild_catch))

lm_k <- lm(ln_wild ~ year_number, data = fish_exp)

# Constant level reached at around 95 = K, catch at year 0 is around 17 so A ~ (95-17)/17 ~ 4.6. lm_k gives us that k = ~0.03.
```

**Figure 1.** The relationship between wild catches and time is described by logistic growth, which is described mathematically as:

$P(t)=\frac{K}{1+Ae^{-kt}}$

Where:

- $K$ is the carrying capacity
- $A$ is $\frac{K-P_0}{P_0}$
- $k$ is the growth rate constant

Our initial estimates are: *k* is around 0.03, *K* is around 95, and *A* is around 4.6. 

### Using nonlinear least squares to find parameters

```{r, results='hide'}
# Using our estimates to run the model
fish_nls <- nls(wild_catch ~ K/(1 + A*exp(-r*year_number)),
              data = fish_catch,
              start = list(K = 95, A = 4.6, r = 0.03),
              trace = TRUE
              )

# Get a summary of the model
summary(fish_nls)

# And use broom to see it in a better format
model_out <- broom::tidy(fish_nls) 
```


```{r}
# Using kable to present a nicer looking table
model_out %>% 
  mutate(p.value = case_when(
    p.value < 0.0001 ~ "< 0.0001"
  )) %>% 
  kbl(col.names = c("Term",
                    "Estimate",
                    "Standard error",
                    "Statistic",
                    "P value")) %>% 
  kable_styling(bootstrap_options = "striped") 

```


Based on these values, our model is:

$$P(t) = \frac{100.23}{1+4.32e^{0.070t}}$$

```{r}
# Making predictions first to be used in a plot comparing our model with the OG data and then binding them
predict <- predict(fish_nls)

fish_complete <- data.frame(fish_catch, predict)

# Making a plot!
ggplot(data = fish_complete, aes(x = year_number, y = wild_catch)) +
  geom_point() +
  geom_line(aes(x = year_number, y = predict)) +
  theme_minimal() +
  labs(x = "Time (years 0 - 62)",
       y = "Wild fish catch",
       title = "Increase in global wild fish catch, 1950-2012")
```

